name: Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      test_value:
        description: 'Test value'
        required: true
        default: false
        type: boolean

jobs:
  main:
    strategy:
      max-parallel: 1
      matrix:
        platform: [Android, iOS]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create file
        run: |
          echo "Running for ${{ matrix.platform }}"
          echo "Platform ${{ matrix.platform }}" >> "${{ matrix.platform }}.txt"

      - name: Print if true
        if: github.event.inputs.test_value == true
        run: echo "Test value is true"

      - name: Print if false
        if: github.event.inputs.test_value == false
        run: echo "Test value is false"

      - name: Print value
        env:
          IS_TEST_VALUE: ${{ github.event.inputs.test_value }}
        run: |
          echo "$(( ${{github.run_number}} + ${{vars.TEST_VAR}} ))"
          is_test_value=$IS_TEST_VALUE
          echo "TEST VALUE: $is_test_value"
          if [ "$is_test_value" = true ] ; then
            echo 'Test value is true'
          else
            echo 'Test value is false'
          fi

      - name: Release test
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          name: v${{ github.run_number }}_${{ github.run_attempt }}
          tag_name: test_tag_${{ github.run_number }}_${{ github.run_attempt }}
          files: "${{ matrix.platform }}.txt"
          fail_on_unmatched_files: true
          token: ${{ secrets.TOKEN_TEST }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "Release - ${{ matrix.platform }} #${{ github.run_number }}"
          make_latest: true
          files: "${{ matrix.platform }}.txt"
