name: Test2

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  main:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test
        run: env

      - name: 'Test output'
        run: |
          echo "Event: ${{ toJSON(github.event) }}"

      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
          script: |
            console.log(`Context: ${JSON.stringify(context)}`);
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "Android.txt"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/Android.txt.zip`, Buffer.from(download.data));

      - name: 'Test'
        run: ls -l

    
